#!/bin/bash

# Install xeus_ug4

mkdir build

cd build

echo $CONDA_DIR

which docker

export UG4_ROOT="/opt/ug4-devel"
echo $UG4_ROOT

cmake -D CMAKE_INSTALL_PREFIX=$CONDA_DIR/envs/notebook -D CMAKE_PREFIX_PATH=$CONDA_DIR/envs/notebook ..

make install
